### PR TITLE
Fixed indentation and arrays in services

### PR DESCRIPTION
**Pull request by belohlavek**

### CODE REVIEW

**Comment by belohlavek** [comment]
@fedenaka keep the getParameters() method. It allows abstraction, provides flexibility and generates an error if no (or all invalid) params are passed.

**Comment by fedenaka** [comment]
Done! Check out and tell me if i have to modify something

**Comment by belohlavek** [comment]
Everything's ok!

**Comment by belohlavek** [comment]
Lol, wrong button :laughing:

**Pull request merged**
